---
abstract: 'Object-oriented ray transfer analysis'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Physics-RayTransfer
no_index:
  directory:
    - t
  file:
    - README.pod
provides:
  Physics::RayTransfer:
    file: lib/Physics/RayTransfer.pm
    version: 0.002
  Physics::RayTransfer::Element:
    file: lib/Physics/RayTransfer.pm
    version: 0.002
  Physics::RayTransfer::Lens:
    file: lib/Physics/RayTransfer.pm
    version: 0.002
  Physics::RayTransfer::Mirror:
    file: lib/Physics/RayTransfer.pm
    version: 0.002
  Physics::RayTransfer::Observer:
    file: lib/Physics/RayTransfer.pm
    version: 0.002
  Physics::RayTransfer::Space:
    file: lib/Physics/RayTransfer.pm
    version: 0.002
requires:
  Carp: 0
  List::Util: 0
  Method::Signatures::Modifiers: 0
  MooseX::Declare: 0
resources:
  bugtracker: https://github.com/jberger/Physics-RayTransfer/issues
  repository: http://github.com/jberger/Physics-RayTransfer/
version: 0.002
